---
title: "R Notebook"
output: html_notebook
---

Third Page
```{r}
# install.packages("RPostgreSQL")
require("RPostgreSQL")
# create a connection
# save the password that we can "hide" it as best as we can by collapsing it
pw <- {"ruser"}

# loads the PostgreSQL driver

drv <- dbDriver("PostgreSQL")
# creates a connection to the postgres database
# note that "con" will be used later in each connection to the database
con <- dbConnect(drv, dbname = "cali_water",
                 host = "localhost", port = 5432,
                 user = "ruser", password = pw)

sql_string <- paste("SELECT * FROM lab_results WHERE (units = 'mg/L' AND county_name = 'Alameda' AND parameter LIKE '%Dissolved%')", sep="")
Lab_results <- data.frame(dbGetQuery(con, sql_string))

startstopyears <- range(format(Lab_results$sample_date, format = "%Y"))
totalrange <- (startstopyears[1]:startstopyears[2])

```



````{r}
sampledate <- subset(Lab_results$sample_date, Lab_results$parameter == "Dissolved Sulfate")
sampleresult <- subset(Lab_results$result, Lab_results$parameter == "Dissolved Sulfate")

workingdate <- subset(sampledate, format(sampledate, format = "%Y") == "1983")
workingresult <- subset(sampleresult, format(sampledate, format = "%Y") == "1983")

plot(workingdate, workingresult, main = "1983 Sulfate", xlab = "Month", ylab = "mg/L")
axis(1, xaxp=c(1, 12, 1))

````

And all of it
````{r}
startstopyears <- range(format(Lab_results$sample_date, format = "%Y"))
totalrange <- (startstopyears[1]:startstopyears[2])

for (i in totalrange)
  {
    sampledate <- subset(Lab_results$sample_date, Lab_results$parameter == "Dissolved Nitrate")
    sampleresult <- subset(Lab_results$result, Lab_results$parameter == "Dissolved Nitrate")
    
    workingdate <- subset(sampledate, format(sampledate, format = "%Y") == i)
    workingresult <- subset(sampleresult, format(sampledate, format = "%Y") == i)
    png(paste(i,"_","Nitrate_lab_results.jpg", sep = ""), width = 1000, height = 1000)
    par(mar = c(25, 5, 5, 5))
    try(plot(workingdate, workingresult, main = paste(i, " Nitrate"), xlab = "Month", ylab = "mg/L"))
    dev.off()
  }
````

````{r}
workingset <- data.frame(subset(Lab_results, format(Lab_results$sample_date, format = "%Y") == 1983))





# Scraps
# for (i in unique(Lab_results$parameter))
#   {
#     sampledate <- subset(Lab_results$sample_date, Lab_results$parameter == i)
#     sampleresult <- subset(Lab_results$result, Lab_results$parameter == i)
#     
#     workingdate <- subset(sampledate, format(sampledate, format = "%Y") == "2000")
#     workingresult <- subset(sampleresult, format(sampledate, format = "%Y") == "2000")
#     
#     png(paste(i,"_","2000_lab_results.jpg", sep = ""), width = 1000, height = 1000)
#     par(mar = c(25, 5, 5, 5))
#     try(plot(workingresult~workingdate, las = 2))
#     dev.off()
#   }




# axis(1, xaxp=c(1, 12, 1), at = c(sort(as.vector(unique(format(sampledate, format = "%m"))))), labels = c(sort(as.vector(unique(format(sampledate, format = "%m"))))))
# lablist<-as.vector(c(1:12))
# text(seq(1, 12, by=1), labels = lablist, srt = 45, pos = 1, xpd = TRUE)





# unique(Lab_results$parameter)
# png(paste("1983_Lead","_","lab_results.jpg", sep = ""), width = 1500, height = 1000)
# par(mar = c(25, 5, 5, 5))

# axis(side = 1, xaxp = seq(0, 12, by = 1), labels = TRUE)
# axis(1, xaxp=c(1, 20, 2), las=2)

# dev.off()
# length(unique(format(sampledate, format = "%m")))
# 
# 
# x <- seq(10,200,10)
# y <- runif(x)
# 
# plot(x,y, xaxt="n")
# axis(1, , las=2)












# 
# vvvvvv
#testing
# ^^^^^^
# 
# 
# unique(sampledate)
# unique(sampledate, format(sampledate, format = "%y"))
# unique(sampledate, format(sampledate, format = "%Y"))
# 
# range(unique(sampledate, format(sampledate, format = "%y")))
# range(unique(sampledate, format(sampledate, format = "%Y")))
# 
# length(unique(sampledate, format(sampledate, format = "%y")))
# length(unique(sampledate, format(sampledate, format = "%Y")))
# 


# 
# vvvvvv
#testing
# ^^^^^^
# 

````